os:
  - linux
  - osx
dist: trusty
language: python
python:
  - "3.6"
  - "nightly"
  - "pypy3-nightly"
before_install:
  - pip3 install --upgrade setuptools
  - pip3 install coveralls colorama setuptools_scm
install:
  - python setup.py install
script:
  - coverage run --source=RichConsole setup.py test
after_success:
  - coveralls
  # - python3 setup.py bdist_wheel
  # - python3 setup.py sdist